spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: JavidanA

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: debug
    org.hibernate : debug