spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: javidan
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com.javidan.blog: debug
    org.hibernate : debug